// Created by JunyoungJung on 2026-09-14.
//
// `mermaid.bundle.js`와 서드파티 고지를 만든다. 출력 폴더는 OUTPUT_DIR로 바꿀 수 있다.
// 기본값은 저장소의 리소스 폴더이며, 에이전트 빌드는 외장 작업 폴더를 지정한다.
import { build } from 'esbuild';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const output = process.env.OUTPUT_DIR ?? '../Resources/WebAssets';
await mkdir(output, { recursive: true });

const result = await build({
    entryPoints: ['mermaid-entry.js'],
    outfile: `${output}/mermaid.bundle.js`,
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: ['safari16'],
    minify: true,
    legalComments: 'eof',
    metafile: true,
    define: { 'process.env.NODE_ENV': '"production"' },
});

const packages = new Set();
for (const input of Object.keys(result.metafile.inputs)) {
    const parts = input.split('/');
    const index = parts.lastIndexOf('node_modules');
    if (index < 0) continue;
    const scoped = parts[index + 1].startsWith('@');
    packages.add(parts.slice(0, index + (scoped ? 3 : 2)).join('/'));
}

const notices = ['SwiftLatexMermaid가 번들한 JavaScript의 서드파티 고지\nGenerated by JunyoungJung on 2026-09-14.\n'];
for (const directory of [...packages].sort()) {
    const manifest = JSON.parse(await readFile(path.join(directory, 'package.json'), 'utf8'));
    const home = manifest.homepage ?? manifest.repository?.url ?? '';
    notices.push(`\n${'='.repeat(72)}\n${manifest.name} ${manifest.version} (${manifest.license ?? 'see license'})\n${home}\n`);
    const files = (await readdir(directory)).filter(name => /^(license|licence|copying|notice)(\.|$|-)/i.test(name));
    if (!files.length) notices.push('License information: see the package repository and the bundled legal comments.\n');
    for (const file of files) {
        try {
            notices.push(`\n${file}\n${await readFile(path.join(directory, file), 'utf8')}\n`);
        } catch {
            // 라이선스가 디렉터리인 패키지. 위의 패키지 고지 줄이 출처를 가리킨다.
        }
    }
}
await writeFile(`${output}/MERMAID-THIRD-PARTY-NOTICES.txt`, notices.join('\n'));
console.log(`Bundled Mermaid. Notices: ${packages.size} packages.`);
